"""add show categories

Revision ID: 352b7aef2108
Revises: d8abd4b5e8d8
Create Date: 2026-08-19 17:09:00.426074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '352b7aef2108'
down_revision: Union[str, Sequence[str], None] = 'd8abd4b5e8d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('categories', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'categories')
    # ### end Alembic commands ###
