"""move content uniqueness to validation

Revision ID: 8ae0f024a87e
Revises: 352b7aef2108
Create Date: 2026-08-19 17:52:42.962881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ae0f024a87e'
down_revision: Union[str, Sequence[str], None] = '352b7aef2108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_content_group_language'), 'episodes', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_content_group_language'), 'episodes', ['content_group', 'language'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
